/** @type {import('tailwindcss').Config} */

const primitives = {
  colors: {
    blue: {
      50: "#e4f5fc",
      100: "#cdecf9",
      200: "#9bd9f3",
      300: "#69c5ed",
      400: "#32b0e7",
      500: "#1895ca",
      600: "#1375a0",
      700: "#0f5b7b",
      800: "#0a3c52",
      900: "#051d28",
      950: "#020d12",
    },
    orange: {
      50: "#feede6",
      100: "#feded2",
      200: "#fdbda5",
      300: "#fc9873",
      400: "#fb7746",
      500: "#fa561a",
      600: "#d73d05",
      700: "#9f2d04",
      800: "#6e1f02",
      900: "#351001",
      950: "#190701",
    },
    green: {
      950: "#021205",
      900: "#05290b",
      800: "#0a5217",
      700: "#0f7b22",
      600: "#13a02d",
      500: "#18ca39",
      400: "#32e753",
      300: "#69ed81",
      200: "#9bf3ab",
      100: "#cdf9d5",
      50: "#e4fce8",
    },
    red: {
      950: "#180101",
      900: "#310202",
      800: "#af8181",
      700: "#930606",
      600: "#c40808",
      500: "#f30a0a",
      400: "#f73b3b",
      300: "#f96c6c",
      200: "#fb9d9d",
      100: "#fdcece",
      50: "#fee7e7",
    },
    gold: {
      950: "#151105",
      900: "#2a2209",
      800: "#584813",
      700: "#826a1c",
      600: "#b09026",
      500: "#d4af37",
      400: "#ddbf60",
      300: "#e5cf85",
      200: "#eedfaf",
      100: "#f6eed5",
      50: "#faf7ea",
    },
    teal: {
      950: "#031111",
      900: "#062321",
      800: "#0c4542",
      700: "#136c68",
      600: "#1a8f89",
      500: "#20b2aa",
      400: "#34dad2",
      300: "#68e4de",
      200: "#97ece8",
      100: "#cbf6f4",
      50: "#e5faf9",
    },
    purple: {
      50: "#f8e4fc",
      100: "#f2cdf9",
      200: "#e49bf3",
      300: "#d769ed",
      400: "#c932e7",
      500: "#ac18ca",
      600: "#8813a0",
      700: "#690f7b",
      800: "#460a52",
      900: "#230529",
      950: "#100212",
    },
    grey: {
      0: "#ffffff",
      50: "#f7f6f9",
      100: "#eceaf0",
      200: "#dcd9e3",
      300: "#cac4d4",
      400: "#bab2c7",
      500: "#a79eb8",
      600: "#84789c",
      700: "#615676",
      800: "#423a50",
      900: "#201c26",
      950: "#110f15",
    },
  },
  spacing: {
    2: "2px",
    4: "4px",
    6: "6px",
    8: "8px",
    12: "12px",
    16: "16px",
    20: "20px",
    24: "24px",
    32: "32px",
    40: "40px",
    full: "999px",
  },
  fontWeight: {
    regular: "400",
    medium: "500",
    semi: "600",
    bold: "700",
  },
  fontFamily: {
    title: "LobsterTwo",
    body: "DegularDemo",
  },
};

module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./pages/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],

  theme: {
    extend: {
      colors: {
        "greyScale-surface-default": primitives.colors.grey[0],
        "greyScale-surface-subtle": primitives.colors.grey[50],
        "greyScale-surface-disabled": primitives.colors.grey[200],

        "greyScale-border-default": primitives.colors.grey[100],
        "greyScale-border-disabled": primitives.colors.grey[200],
        "greyScale-border-darker": primitives.colors.grey[700],

        "greyScale-text-negative": primitives.colors.grey[50],
        "greyScale-text-disabled": primitives.colors.grey[400],
        "greyScale-text-caption": primitives.colors.grey[500],
        "greyScale-text-subtitle": primitives.colors.grey[600],
        "greyScale-text-body": primitives.colors.grey[800],
        "greyScale-text-title": primitives.colors.grey[900],
        "greyScale-text-icon": primitives.colors.grey[900],

        "primary-surface-darker": primitives.colors.purple[700],
        "primary-surface-lighter": primitives.colors.purple[300],
        "primary-surface-default": primitives.colors.purple[500],
        "primary-surface-subtle": primitives.colors.purple[50],

        "primary-border-darker": primitives.colors.purple[700],
        "primary-border-lighter": primitives.colors.purple[300],
        "primary-border-default": primitives.colors.purple[500],
        "primary-border-subtle": primitives.colors.purple[50],

        "primary-text-label": primitives.colors.purple[700],
        "primary-text-lighter": primitives.colors.purple[300],
        "primary-text-default": primitives.colors.purple[500],
        "primary-text-subtle": primitives.colors.purple[50],
        "primary-text-icon": primitives.colors.purple[500],

        "accent1-surface-darker": primitives.colors.teal[700],
        "accent1-surface-lighter": primitives.colors.teal[300],
        "accent1-surface-default": primitives.colors.teal[500],
        "accent1-surface-subtle": primitives.colors.teal[50],

        "accent1-border-darker": primitives.colors.teal[700],
        "accent1-border-lighter": primitives.colors.teal[300],
        "accent1-border-default": primitives.colors.teal[500],
        "accent1-border-subtle": primitives.colors.teal[50],

        "accent1-text-label": primitives.colors.teal[700],
        "accent1-text-lighter": primitives.colors.teal[300],
        "accent1-text-default": primitives.colors.teal[500],
        "accent1-text-subtle": primitives.colors.teal[50],
        "accent1-text-icon": primitives.colors.teal[500],

        "accent2-surface-darker": primitives.colors.gold[700],
        "accent2-surface-lighter": primitives.colors.gold[300],
        "accent2-surface-default": primitives.colors.gold[500],
        "accent2-surface-subtle": primitives.colors.gold[50],

        "accent2-border-darker": primitives.colors.gold[700],
        "accent2-border-lighter": primitives.colors.gold[300],
        "accent2-border-default": primitives.colors.gold[500],
        "accent2-border-subtle": primitives.colors.gold[50],

        "accent2-text-label": primitives.colors.gold[700],
        "accent2-text-lighter": primitives.colors.gold[300],
        "accent2-text-default": primitives.colors.gold[500],
        "accent2-text-subtle": primitives.colors.gold[50],
        "accent2-text-icon": primitives.colors.gold[500],

        "success-surface-darker": primitives.colors.green[700],
        "success-surface-lighter": primitives.colors.green[300],
        "success-surface-default": primitives.colors.green[500],
        "success-surface-subtle": primitives.colors.green[50],

        "success-border-darker": primitives.colors.green[700],
        "success-border-lighter": primitives.colors.green[300],
        "success-border-default": primitives.colors.green[500],
        "success-border-subtle": primitives.colors.green[50],

        "success-text-label": primitives.colors.green[700],
        "success-text-lighter": primitives.colors.green[300],
        "success-text-default": primitives.colors.green[500],
        "success-text-subtle": primitives.colors.green[50],
        "success-text-icon": primitives.colors.green[500],

        "error-surface-darker": primitives.colors.red[700],
        "error-surface-lighter": primitives.colors.red[300],
        "error-surface-default": primitives.colors.red[500],
        "error-surface-subtle": primitives.colors.red[50],

        "error-border-darker": primitives.colors.red[700],
        "error-border-lighter": primitives.colors.red[300],
        "error-border-default": primitives.colors.red[500],
        "error-border-subtle": primitives.colors.red[50],

        "error-text-label": primitives.colors.red[700],
        "error-text-lighter": primitives.colors.red[300],
        "error-text-default": primitives.colors.red[500],
        "error-text-subtle": primitives.colors.red[50],
        "error-text-icon": primitives.colors.red[500],

        "warning-surface-darker": primitives.colors.orange[700],
        "warning-surface-lighter": primitives.colors.orange[300],
        "warning-surface-default": primitives.colors.orange[500],
        "warning-surface-subtle": primitives.colors.orange[50],

        "warning-border-darker": primitives.colors.orange[700],
        "warning-border-lighter": primitives.colors.orange[300],
        "warning-border-default": primitives.colors.orange[500],
        "warning-border-subtle": primitives.colors.orange[50],

        "warning-text-label": primitives.colors.orange[700],
        "warning-text-lighter": primitives.colors.orange[300],
        "warning-text-default": primitives.colors.orange[500],
        "warning-text-subtle": primitives.colors.orange[50],
        "warning-text-icon": primitives.colors.orange[500],

        "info-surface-darker": primitives.colors.blue[700],
        "info-surface-lighter": primitives.colors.blue[300],
        "info-surface-default": primitives.colors.blue[500],
        "info-surface-subtle": primitives.colors.blue[50],

        "info-border-darker": primitives.colors.blue[700],
        "info-border-lighter": primitives.colors.blue[300],
        "info-border-default": primitives.colors.blue[500],
        "info-border-subtle": primitives.colors.blue[50],

        "info-text-label": primitives.colors.blue[700],
        "info-text-lighter": primitives.colors.blue[300],
        "info-text-default": primitives.colors.blue[500],
        "info-text-subtle": primitives.colors.blue[50],
        "info-text-icon": primitives.colors.blue[500],
      },
      fontSize: {
        display: "64px",
        title: "48px",
        subtitle: "32px",
        heading: "25px",
        subheading: "20px",
        body: "16px",
        "body-medium": "14px",
        "body-small": "12px",
        caption: "10px",
      },
      fontWeight: {
        regular: primitives.fontWeight.regular,
        medium: primitives.fontWeight.medium,
        semi: primitives.fontWeight.semi,
        bold: primitives.fontWeight.bold,
      },
      fontFamily: {
        title: primitives.fontFamily.title,
        body: primitives.fontFamily.body,
      },
      borderRadius: {
        x: "2px",
        s: "4px",
        m: "8px",
        l: "12px",
        xl: "16px",
        full: "999px",
      },
    },
    plugins: [],
  },
};
